### ISSUE TITLE
document `action_event` 

### ISSUE THREAD

**Issue by rattrayalex** [hired/reactor#33]
It's undocumented... so when you go looking for where events might come from, you don't know to look for that one!

**Comment by wnadeau** [comment]
Oddly enough, it's not exactly part of `Reactor` proper. It's more of the client-side wrapper that any `Reactor` consuming application can write for themselves to fire `Reactor::Event.publish` with whatever default data they want. 

If this behavior were to live in `Reactor`, it'd have to be in a controller concern, I imagine. The justification for this thing to live in reactor or not really depends on the philosophy behind what reactor is.

Is reactor just one component in an ecosystem, merely a handy pub-sub wrapper around sidekiq jobs. Or is it a mini-ecosystem of conventions to apply to a rails app?

These days I'm leaning toward keeping `Reactor` a small component because it's non-trivial to scale conventions to larger teams. I used to dream about it being a bigger basket of conventions that I could take with me to scale a data pipeline around any rails app, but I've gotten more conservative with ambitions lately.

**Comment by wnadeau** [comment]
Given that context, I'm curious which philosophical perspective you have absorbed about Reactor as a user. Do you lean either way? The current implementation is sort of straddling both, unfortunately, as a result of my own personal flip-flopping on it. I do hope to get to some of these "things I've realized about Reactor" at our next hackathon.

**Comment by rattrayalex** [comment]
Oh, I didn't know that! Makes sense. No, I think keeping as-is seems logical. Thanks!

**Comment by wnadeau** [comment]
😃 

👋  hey @rattrayalex miss ya buddy, hope you're doing well

**Comment by rattrayalex** [comment]
Hehe hi Winfred! Closing out the ol issues eh. Surprised this lingered as long as it did.

**Comment by bananatron** [comment]
👋 🐈
